// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5pmZSrMsYJQHk2C7VRrvCqQ5rUR9HsJw',
    appId: '1:821927825443:android:2561fb12eed77ec653a196',
    messagingSenderId: '821927825443',
    projectId: 'fir-30dab',
    storageBucket: 'fir-30dab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQXxbG6dilDI7IKH56YUIFY2kXBbF_4VU',
    appId: '1:821927825443:ios:5954b2e48a6120df53a196',
    messagingSenderId: '821927825443',
    projectId: 'fir-30dab',
    storageBucket: 'fir-30dab.appspot.com',
    androidClientId: '821927825443-m2uec3dp6grtghp9vtkkq35egiko55gf.apps.googleusercontent.com',
    iosClientId: '821927825443-e8iblorqnc0d2ub1tg0ivp3duuip1l31.apps.googleusercontent.com',
    iosBundleId: 'com.islam.todo.toDoFirebase',
  );
}
